apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ueaq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-ueaq@sha256:72f526a74c2c3cc840f14b40644c150a656bfd9c5a7138a1b10cfea825f2ed65
        name: my-nodejs
        resources: {}
status: {}
